name: ci

on: 
  push:
    branches: [ master, dev ]

env:
  PACKAGE_NAME: 'vercel-deno-dev'

jobs:
  test:
    needs: build
    strategy:
      matrix:
        os: ['ubuntu-latest']
        node: ['12.x']
        deno: ['1.0.5']
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: test-${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
      - name: Setup deno
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ matrix.deno }}
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: yarn install
      - name: Install vercel
        run: npm i -g vercel
        if: matrix.os == 'windows-latest'
      - name: Update package version and tag
        run: deno run --unstable --allow-env --allow-read --allow-write .github/workflows/update-version.ts
      - name: Run tests
        run: deno test --unstable --allow-env --allow-read --allow-write --allow-net=localhost --allow-run .github/workflows/tests.ts
        env:
          NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
